name: padp

version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    restart: always
    networks:
      - padp-network
    depends_on:
      - range-classical-ctf
      - range-classical-communication
      - range-classical-crack

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
      - "3002:3002"
    restart: always
    depends_on:
      - backend
    networks:
      - padp-network

  # 古典密码靶场
  range-classical-ctf:
    build:
      context: ./docker/range-classical-ctf
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - padp-network

  range-classical-communication:
    build:
      context: ./docker/range-classical-communication
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    networks:
      - padp-network

  range-classical-crack:
    build:
      context: ./docker/range-classical-crack
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    networks:
      - padp-network

  # DES弱密钥靶场
  range-des-weak:
    build:
      context: ./docker/range-des-weak
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always
    networks:
      - padp-network

networks:
  padp-network:
    driver: bridge
